### PR TITLE
Updated audio effect

### PR DESCRIPTION
**Pull request by inikonorov**
Hi! I've updated key pressed sound file (from .mp3 to .webm), can you test it?

### CODE REVIEW

**Comment by amitguptagwl** [comment]
@inikonorov it was my bad. You enabled it for 11th line, that I didn't notice. However now I've changed the sound file, and  little bit of implementation Please check

**Comment by inikonorov** [comment]
Oh, thanks 
It looks great (I'm about code)
But I thought that I need add sound only for "you typing tweets" string (from issue `Give small key press sound . Line number 126`)
And because of it I did it without .play() method, because this method calls error, so I made it via .append() and .remove() methods
I didn't understand you correctly, sorry for this, I could do it better

**Comment by inikonorov** [comment]
And also I thought that I need use sound only when "I click on keyboard buttons (beside return, backspace, etc)"

**Comment by amitguptagwl** [comment]
@inikonorov it happens. But we should clear our doubts and assumption. Both side can be unable to express their thoughts in one go.

**Comment by inikonorov** [comment]
okay, I will ask you if I will have any questions :)

**Pull request merged**
