### PR TITLE
Added buttons on demo

### PR DESCRIPTION
**Pull request by ashishpatelcs**
Added buttons and replaced div with a flexbox. The button classes and texts are changed on clicks.

### CODE REVIEW

**Comment by ashishpatelcs** [comment]
The bootstrap classes made the buttons far apart. sometimes outside the keyboard boundaries. Please refer to some layout example how it should look, i'll change accordingly.

**Comment by amitguptagwl** [comment]
I'm working with bootstrap from a long time so I'm aware with their look. But I still understand your concern. Can you please share some image to highlight the difference you want me to notice?

**Comment by ashishpatelcs** [comment]
I have changed everything back to only use bootstrap. except the 5px margin to the right i have added to buttons to make them not stick to each other. Even after 5px margin, the buttons are slightly outside the keyboard area. I wanted to perfectly align them along with the keyboard for a streamlined UI.

**Comment by amitguptagwl** [comment]
Just remove `text-right` from `<div class="col-12 text-right">` and everything will look fine.

**Comment by ashishpatelcs** [comment]
removed that class.

**Pull request merged**
