### PR TITLE
Added buttons on demo

### PR DESCRIPTION
**Pull request by ashishpatelcs**

### CODE REVIEW

**Comment by amitguptagwl** [comment]
I haven't checked your changes yet. But there are 2 changes needed;

1. Use icons instead of text on buttons. It 'll allow fitting more buttons in the toolbar in future.
2. Once a button is pressed its color should be changed so that user know if it is selected.

**Comment by ashishpatelcs** [comment]
@amitguptagwl my demo can be seen at https://ashishpatelcs.github.io/shabdawali/
can you point me to some icons?

**Comment by ashishpatelcs** [comment]
Oh, I was not aware that you can preview this way. Thanks.

**Comment by amitguptagwl** [comment]
Hmm!! good point. Probably You can use pipe sign for show cursor button and 90 degree rotated "=" for pause with tooltip (alt attribute). Otherwise, we'll have to think. Nothing particular on top of my head currently.

**Comment by ashishpatelcs** [comment]
For now, I've changed buttons names to 'Show Cursor', 'Keypress Sound' and 'Dynamic Pause' to make them smaller.

**Comment by amitguptagwl** [comment]
It looks good. The only necessary thing is left to change the color or button when it is selected.

**Comment by ashishpatelcs** [comment]
Ok, working on it.

**Comment by ashishpatelcs** [comment]
Seems like new PR has conflicts. I'll push a new PR.

**Pull request closed without merging**
